test_zip_iterator.cpp ported from xip_iterator.cu
The 2 tests with #if 0 disabled parts (essentially the whole tests) give "undefined reference to `thrust::detail::integral_constant<bool, true>::value'" Which is also mentioned in the .cu version.


[ROCm/rocThrust commit: 70d13f8772b260d1127320b53a961f1a08bbd6fe]